---
name: "🎨 Lint"

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]' && !contains(github.event.head_commit.message, '[skip lint]')

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "🎨 Super-Linter"
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_MARKDOWN: false
          VALIDATE_NATURAL_LANGUAGE: false
